- debug: var=item
- name: set filter
  command: >
    hammer --output json content-view filter rule update
    --organization "{{ organization }}"
    --content-view "{{ item.content_view }}"
    --content-view-filter "Staging-erratum"
    --id "{{ item.filter_rule_id }}"
    --end-date "{{ item.content_view_date_filter }}"
- name: publish content view
  command: >
    hammer content-view publish
    --organization "{{ organization }}"
    --name "{{ item.content_view }}"
    --description "hailstorm-{{ item.content_view_date_filter }}"
